### ISSUE TITLE
The values of splinters and shards are inaccurate

### ISSUE THREAD

**Issue by FoolMoon** [viktorgullmark/exilence-next#525] opened 2020-04-04 09:42 UTC
**Is your feature request related to a problem? Please describe.**
The values of various splinters and shards don't match reality, and have prices that are much bigger than they should be.

For example, Exilence currently shows has Splinter of Esh valued at 0.33c (~0.6c on poe.ninja and 5c on poe.watch). All of these values are obviously wrong, because a full Esh's Breachstone costs less than 3c, so it wouln't be realistic to sell the splinters at those values. Same problem exists with most other splinters and shards.

**Describe the solution you'd like**
The splinter and shard values (except the ones that are actually valuable, like Mirror and Exalt shards) should be based on the value of the completed item they give. For example, the value of a Splinter of Esh would be equal to the value of Esh's Breachstone divided by 100.

**Comment by viktorgullmark** [comment] 2020-04-04 15:18
If it's different from poe.ninja the problem is your price league setting most likely. We will not price these ourselves and will most likely always use an external price source as poe.ninja or poe.watch, so I will close this. 

If you think our values in Exilence are faulty with the proper price league set, comment here and we'll see if we can find the issue.

**Closed by viktorgullmark** 2020-04-04 15:18 UTC
