### ISSUE TITLE
Option to not update Ninja prices

### ISSUE THREAD

**Issue by petterannerwall** [viktorgullmark/exilence-next#566] opened 2020-09-17 14:03 UTC
Useful if you want to do calculations over several maps or a period of time and want to compare the results.

**Comment by petterannerwall** [comment] 2020-09-17 14:04
Useful if you want to do calculations over several maps or a period of time and want to compare the results.

**Comment by viktorgullmark** [comment] 2021-09-22 21:35
Closing, duplicate of #708

**Closed by viktorgullmark** 2021-09-22 21:35 UTC
Labels: frontend, feature
