### ISSUE TITLE
Logging in via the browser does not log in

### ISSUE THREAD

**Issue by fkeet** [viktorgullmark/exilence-next#700] opened 2021-07-31 19:27 UTC
**Describe the bug**
From the main Excilence window the login with pathofexile.com button opens a browser window, but authorizing in the browser window does not authorize the app.

**To Reproduce**
1 Open Exilence Next
2 Click 'Log in with pathofexile.com' button with 'PC' selected
3 In browser window click 'Authorize'
4 Nothing happens

**Expected behavior**
I expect Exilence Next to now continue with authorization

**Version**
v0.5.0

**Additional context**
Using Firefox 90.0.2

**Comment by sbsrnt** [comment] 2021-08-01 18:59
Wthat is your OS? Linux & MacOS are not supported yet

**Comment by fkeet** [comment] 2021-08-02 21:06
I assumed so, unfortunately I'm using Windows.

**Comment by sbsrnt** [comment] 2021-08-03 12:48
Seems like this is affecting few users and another thing that comes to my mind is maybe your OS / browser / antivirus are blocking [custom protocols](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/registerProtocolHandler/Web-based_protocol_handlers) (in our case it's `exilence`)

The last thing that comes to my mind is that we probably didn't register custom protocols  properly for windows users which may be covered in https://github.com/viktorgullmark/exilence-next/pull/692

**Comment by fkeet** [comment] 2021-08-03 19:14
Thank you, I'll check on that.

**Comment by oplosthee** [comment] 2021-08-06 19:37
> What is your OS? Linux & MacOS are not supported yet
> 
> Edit: make sure you have popouts enabled on poe website

Is Linux support something that is planned for the future? I remember having used Exilence during the previous league locally, which seemed to work fine, but like you mentioned the API authentication doesn't work at the moment.

Or if there are instructions available on how to set this up on Linux, that would be great too! Thanks for your work!

**Comment by elmo667** [comment] 2021-08-08 12:18
Happens on Linux too, used to work fine in previous versions (will have to revert for now).    
    
The problem is that Exilence Next does not register the exilence.next.app protocol with the OS/Firefox so the redirect to the local exilence fails. If we can find out where that is done in the code for windows, it might be possible to self-add the protocol to Firefox.

**Comment by sbsrnt** [comment] 2021-08-08 18:47
https://github.com/viktorgullmark/exilence-next/pull/692

**Comment by elmo667** [comment] 2021-08-09 16:27
thanks for this! I pulled the master repo after the PR got merged. @sbsrnt the behaviour is unchanged. Firefox is still confused about what to even do with the link:
> Prevented navigation to “https://next.exilence.app/api/authentication/redirect?code=<REDACTED>” due to an unknown protocol.    
    
Chromium console says:
>Launched external handler for 'exilence://?code=<REDACTED1>&state=<REDACTED2>'
but nothing happens.

From what I understand it needs to add itself to $HOME/.local/share/applications/mimeinfo.cache and it has not done that. Discord has done that. Zoom hasnt (and zoom links arent working as a result).

I would like to help diagnosing/debugging this but Im not versed in reading js (and the tons of node modules dont exactly make it any easier ;)). What is it Exilence does? What can I check for that it shouldve done/added? The mime-registration seems to be missing at least.

Am also happy to pull new test builds.

**Comment by sbsrnt** [comment] 2021-08-13 10:12
For those that want to have the issue fixed before release and are on windows

1. Type in windows search `regedit`
![image](https://user-images.githubusercontent.com/19862545/129341303-13f16e11-f036-4be0-8ba1-6da19ef5c70e.png)

2.  Navigate to this path Computer\HKEY_CLASSES_ROOT\exilence
![image](https://user-images.githubusercontent.com/19862545/129341398-62846506-f191-408e-9f55-9225e8b1a566.png)

3. Select exilence
![image](https://user-images.githubusercontent.com/19862545/129341421-d7ac6c9d-5096-4fe1-acdb-9cafde6ec98a.png)

4. Double click on 
![image](https://user-images.githubusercontent.com/19862545/129341522-4805f234-23cf-4508-bf01-94cc1d9b6276.png)

5. add value `URL:exilence` and click OK
![image](https://user-images.githubusercontent.com/19862545/129341585-ff9a17d5-abff-46cb-bf0e-930ccc1882e4.png)

6. right click anywhere in the empty space and create a new string
![image](https://user-images.githubusercontent.com/19862545/129341668-edd6821c-e4cf-47cc-8587-7e719df4ba7b.png)

7. type `URL Protocol`
![image](https://user-images.githubusercontent.com/19862545/129341870-d4c29470-ab38-4dd9-a38b-85f05a5d7cee.png)

**Comment by sbsrnt** [comment] 2021-08-13 20:45
Most likely fixed in 0.5.4

**Closed by sbsrnt** 2021-08-13 20:45 UTC
