### ISSUE TITLE
Can no longer get snapshots.

### ISSUE THREAD

**Issue by niicholai** [viktorgullmark/exilence-next#821] opened 2022-03-13 03:50 UTC
**Describe the bug**
When I try to take a snapshot I receive 2 toast errors.  Was working fine a week or so ago when I last used it.

1. Failed to create snapshot.  The snapshot could not be created.

2. Failed retrieving items for Archnemesis. Request failed with status code 404.

**To Reproduce**
1. Go to Exilence Next
2. Click on Take Snapshot
3. See error

**Expected behavior**
For EN to take a snapshot, not throw errors.

**Screenshots**
https://imgur.com/rpe08vN

**Version**
1.1.8

**Comment by settonull** [comment] 2022-06-27 20:35
I'm having the exact same issue.   I've tried logging out and re-authorizing and resetting data without fixing it, going to try a reinstall next.

**Comment by viktorgullmark** [comment] 2022-08-21 20:21
The reason for this is usually that a league or character stops existing. Could be that a league is finished or that a character in HC has died, or changed name. Same thing can happen if the stash tab changes in some way. Closing this, reopen if you cant find out the cause from the list I gave!

**Closed by viktorgullmark** 2022-08-21 20:21 UTC
