### ISSUE TITLE
Request failed with status code 429

### ISSUE THREAD

**Issue by CubeStick** [viktorgullmark/exilence-next#791] opened 2021-11-14 08:44 UTC
**Describe the bug**
Fresh install, configured the profile and get this error:
Initialize session failed
a few seconds ago — Request failed with status code 429

**To Reproduce**
1. Open Exilence
2. Configure profile
3. See error

**Expected behavior**
I expect it to display my data.

**Version**
Latest, 1.1.6

**Comment by JReko** [comment] 2021-12-09 16:32
Most likely not a bug, POE's API is rate limited, a 429 means you are making too many requests (https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429) and hitting that rate limit your session ID.

It can be because of using multiple tools at the same time like Exilence and Awakaned POE Trade for example.

**Comment by strey1998** [comment] 2021-12-18 20:16
I've been having this issue even when I exit my trade tool (the only other tool accessing my account). A lot of the 429s say either "Initialize session failed" or "Failed retrieving stash tabs for <League>". A lot of the latter reference private leagues which no longer exist and sometimes haven't for several months. If I manage to hit the "Take Snapshot" button between rate limit timeouts, it successfully takes a snapshot before immediately returning to many of the mentioned errors and timing out again.

**Comment by LaydMartin** [comment] 2022-01-10 19:41
Failed retrieving stash tabs for Expedition
a few seconds ago — Request failed with status code 429

Expedition? Maybe this is the reason and for this there are many requests. Your program asks for old leagues or events that have already passed, while making requests to them constantly.

**Comment by pryczyk** [comment] 2022-02-18 22:08
I am having the same issue.  I've fresh installed 1.1.7 and turned off all other third party tools.  The issue is not that I am trying to take a snapshot but the program is constantly trying to initialize session and fetch stash tabs for leagues that either don't exist or that I've never played.  At the moment my screen has 7 instances of "Intialize session failed" and 2 instances of "Failed retrieving stash tabs for SSF Standard"

**Comment by strey1998** [comment] 2022-02-19 03:08
Yep. As of this league the app is completely unusable because it fails to even retrieve my list of stash tabs in Archnemesis. I hope this gets some attention.

**Comment by pryczyk** [comment] 2022-03-20 17:30
Still having this issue.  Seems others are as well.

**Comment by strey1998** [comment] 2022-03-20 17:59
Going to advanced settings and resetting data mostly fixed it for me. Only a couple of defunct leagues appear now, and I rarely get rate limited.

**Comment by pjaws** [comment] 2022-06-22 22:34
I've also tried resetting my data, and now the app just won't even initialize. I get the "Initialize session failed"/429 error right off the bat and can't even create a profile.

**Comment by viktorgullmark** [comment] 2022-08-21 20:43
This should be resolved with the latest version. Let us know if this still occurs (feel free to reopen the issue)!

**Closed by viktorgullmark** 2022-08-21 20:43 UTC
